//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.ModelsD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public string Category { get; set; }
        public string BookName { get; set; }
        public string ReviewType { get; set; }
        public string BookSubject { get; set; }
        public string BookAnalysis { get; set; }
        public string AuthorName { get; set; }
        public string OtherBooks { get; set; }
    }
}
